name: Docker publish

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
env:
  DOCKER_USER: enho
  DOCKER_ORG: quantrams
  DOCKER_REPO: tvscraper
  DOCKER_TAG: 1.0.0
  TV_USER: ethannho

jobs:

  build-test-push:
    name: Build, test, and run image
    runs-on: ubuntu-latest
    steps:
        # install dependencies
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install Python dependencies
        run: python -m pip install -q virtualenv poetry
      
      # build
      - name: Build dist
        run: poetry build
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ env.DOCKER_ORG }}/${{ env.DOCKER_REPO }}:${{ env.DOCKER_TAG }}
      
      # run tests in Docker image
      # native python won't work because chromedriver
      - name: Run tests in Docker
        run: |
          docker run --rm -it -v /dev/shm:/dev/shm --env TV_USER=${{ env.TV_USER }} --env TV_PASS=${{ secrets.TV_PASS }} ${{ env.DOCKER_ORG }}/${{ env.DOCKER_REPO }}:${{ env.DOCKER_TAG }} 

      # push
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_ORG }}/${{ env.DOCKER_REPO }}:${{ env.DOCKER_TAG }}
            ${{ env.DOCKER_ORG }}/${{ env.DOCKER_REPO }}:latest